{{- if $.Values.gangplank.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gangplank.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gangplank.labels" . | nindent 4 }}
{{- if .Values.gangplank.service.labels }}
  {{ toYaml .Values.gangplank.service.labels | nindent 4 }}
{{- end }}
{{- with .Values.gangplank.service.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
{{- end }}
spec:
{{- if (or (eq .Values.gangplank.service.type "ClusterIP") (empty .Values.gangplank.service.type)) }}
  type: ClusterIP
  {{- if .Values.gangplank.service.clusterIP }}
  clusterIP: {{ .Values.gangplank.service.clusterIP }}
  {{end}}
{{- else if eq .Values.gangplank.service.type "LoadBalancer" }}
  type: {{ .Values.gangplank.service.type }}
  {{- if .Values.gangplank.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.gangplank.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.gangplank.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.gangplank.service.loadBalancerSourceRanges | indent 4 }}
  {{- end -}}
{{- else }}
  type: {{ .Values.gangplank.service.type }}
{{- end }}
  ports:
  - name: http
    port: {{ .Values.gangplank.service.port }}
    protocol: TCP
    targetPort: http
    {{ if (and (eq .Values.gangplank.service.type "NodePort") (not (empty .Values.gangplank.service.nodePort))) }}
      {{- if .Values.gangplank.service.nodePort }}
    nodePort: {{.Values.gangplank.service.nodePort}}
      {{- end }}
    {{ end }}
  selector:
    {{- include "gangplank.selectorLabels" . | nindent 4 }}
{{- end }}
