linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/projectcapsule/capsule-proxy)
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  cyclop:
    max-complexity: 17
linters:
  enable-all: true
  disable:
    - errchkjson
    - errname
    - forcetypeassert
    - ireturn
    - varnamelen
    - wrapcheck
    - gomnd
    - lll
    - nonamedreturns
    - tparallel
    - nilerr
    - exhaustruct
    - depguard
    # should be enabled
    - revive
    - err113
    - mnd
    - nilnil
    - wsl
    - perfsprint

    # deprecated
    - exportloopref
    - execinquery