linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/projectcapsule/capsule-proxy)
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  cyclop:
    max-complexity: 17
issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - revive
      text: "^(dot-imports)"
linters:
  enable-all: true
  disable:
    - err113
    - mnd
    - errchkjson
    - errname
    - forcetypeassert
    - ireturn
    - varnamelen
    - wrapcheck
    - gomnd
    - lll
    - nonamedreturns
    - tparallel
    - nilerr
    - exhaustruct
    - depguard
    - revive
    - nilnil
    - wsl
    - perfsprint
    - exportloopref
    - execinquery
    - forcetypeassert
