{{- if .Values.crds.install }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "capsule-proxy.crds.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    "helm.sh/hook-weight": "-1"
    {{- include "capsule-proxy.crds.annotations" . | nindent 4 }}
    {{- with .Values.global.jobs.kubectl.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    app.kubernetes.io/component: {{ include "capsule-proxy.crds.component" . | quote }}
    {{- include "capsule-proxy.labels" . | nindent 4 }}
    {{- with .Values.global.jobs.kubectl.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ttlSecondsAfterFinished: {{ .Values.global.jobs.kubectl.ttlSecondsAfterFinished }}
  template:
    metadata:
      name: "{{ include "capsule-proxy.crds.name" . }}"
      annotations:
        {{- with .Values.global.jobs.kubectl.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/component: {{ include "capsule-proxy.crds.component" . | quote }}
        {{- include "capsule-proxy.selectorLabels" . | nindent 8 }}
        {{- with .Values.global.jobs.kubectl.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: {{ $.Values.global.jobs.kubectl.restartPolicy }}
      {{- if $.Values.global.jobs.kubectl.podSecurityContext.enabled }}
      securityContext: {{- omit $.Values.global.jobs.kubectl.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.global.jobs.kubectl.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.jobs.kubectl.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.jobs.kubectl.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.jobs.kubectl.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.jobs.kubectl.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "capsule-proxy.crds.name" . }}
      containers:
      - name: crds-hook
        image: {{ include "capsule-proxy.kubectlFullyQualifiedDockerImage" . }}
        imagePullPolicy: {{ .Values.global.jobs.kubectl.image.pullPolicy }}
        {{- if .Values.global.jobs.kubectl.securityContext.enabled }}
        securityContext: {{- omit .Values.global.jobs.kubectl.securityContext "enabled" | toYaml | nindent 10 }}
        {{- end }}
        command:
        - sh
        - -c
        - |
          set -o errexit ; set -o xtrace ; set -o nounset

          # piping stderr to stdout means kubectl's errors are surfaced
          # in the pod's logs.

          kubectl apply --server-side=true --overwrite=true --force-conflicts=true -f /data/ 2>&1
        volumeMounts:
{{- range $path, $_ := .Files.Glob "crds/**.yaml" }}
        - name: {{ $path | base | trimSuffix ".yaml" | regexFind "[^_]+$" }}
          mountPath: /data/{{ $path | base }}
          subPath: {{ $path | base }}
{{- end }}
        {{- with .Values.global.jobs.kubectl.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
{{ $currentScope := . }}
{{- range $path, $_ := .Files.Glob "crds/**.yaml" }}
    {{- with $currentScope }}
      - name: {{ $path | base | trimSuffix ".yaml" | regexFind "[^_]+$" }}
        configMap:
          name: {{ include "capsule-proxy.crds.name" $ }}-{{ $path | base | trimSuffix ".yaml" | regexFind "[^_]+$" }}
          items:
          - key: content
            path: {{ $path | base }}
{{- end }}
{{- end }}
  backoffLimit: 4
{{- end }}
