{{- if $.Values.webhooks.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "capsule-proxy.fullname" . }}-webhook
  labels:
    {{- include "capsule-proxy.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "capsule-proxy.fullname" . }}-webhook-cert
webhooks:
  {{- with .Values.webhooks.watchdog }}
    {{- if .enabled }}
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- include "capsule-proxy.webhooks.service" (dict "path" "/mutate/watchdog" "ctx" $) | nindent 4 }}
  failurePolicy: {{ .failurePolicy }}
  name: watchdog.proxy.projectcapsule.dev
  {{- with .rules }}
  rules:
    {{- toYaml .| nindent 4}} 
  {{- end }}
  {{- with .namespaceSelector }}
  namespaceSelector:
    {{- toYaml .| nindent 4}} 
  {{- end }}
  sideEffects: None
  timeoutSeconds: {{ $.Values.webhooks.mutatingWebhooksTimeoutSeconds }}
    {{- end }}
  {{- end }}
{{- end }}
