apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
# networking:
#   apiServerAddress: "127.0.0.1"
#   apiServerPort: 6443
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
      - hostPort: 9001
        containerPort: 9001
  - role: worker
