crds:
  install: true
  keep: false
global:
  jobs:
    certs:
      nodeSelector:
        global-field: "global-value"
jobs:
  certs:
    registry: custom-registry
    repository: jettech/kube-webhook-certgen
    pullPolicy: IfNotPresent
    tag: "v1.5.2"
