crds:
  install: true
  keep: false
rbac:
  annotations:
    extra: annotation
  labels:
    extra: label
kind: Deployment
imagePullSecrets: []
certManager:
  generateCertificates: true
  externalCA:
    enabled: false
    # secret containing the CA cert and private key of the external CA in the correct cert-manager format as per https://cert-manager.io/docs/configuration/ca/#deployment
    secretName: ""
  issuer:
    kind: Issuer # Issuer or ClusterIssuer
    name: "" #  Name of the ClusterIssuer
replicaCount: 1
podAnnotations:
  extra: annotation
podLabels:
  extra: label
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: capsule-proxy
priorityClassName: "system-node-critical"
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 200m
    memory: 128Mi
autoscaling:
  enabled: true
  annotations:
    example: annotation
  labels:
    example: label
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  metrics:
  - type: Pods
    pods:
      metric:
        name: packets-per-second
      target:
        type: AverageValue
        averageValue: 1k
  behavior:
    scaleDown:
      policies:
      - type: Pods
        value: 4
        periodSeconds: 60
      - type: Percent
        value: 10
        periodSeconds: 60
service:
  annotations:
    example: annotation
  labels:
    example: label
ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    example: annotation
  labels:
    example: label
  hosts:
  - host: "kube.clastix.io"
    paths: ["/"]
  tls:
  - hosts:
      - kube.clastix.io
    secretName: capsule-proxy-tls
# ServiceMonitor
serviceMonitor:
  enabled: true
