crds:
  install: true
  keep: false
kind: DaemonSet
daemonset:
  hostNetwork: true
  hostPort: true
service:
  nodePort: 30901
imagePullSecrets: []
certManager:
  generateCertificates: true
  externalCA:
    enabled: false
    # secret containing the CA cert and private key of the external CA in the correct cert-manager format as per https://cert-manager.io/docs/configuration/ca/#deployment
    secretName: ""
  issuer:
    kind: Issuer # Issuer or ClusterIssuer
    name: "" #  Name of the ClusterIssuer
replicaCount: 1
podAnnotations:
  extra: annotation
podLabels:
  extra: label
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: capsule-proxy
priorityClassName: "system-node-critical"
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 200m
    memory: 128Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
nodeSelector:
  node-role.kubernetes.io/master: ""
tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: another-node-label-key
          operator: In
          values:
          - another-node-label-value
# Ingress
ingress:
  enabled: true
  ingressClassName: "nginx"
  hosts:
  - host: "kube.clastix.io"
    paths: ["/"]
  tls:
  - hosts:
      - kube.clastix.io
    secretName: capsule-proxy-tls
# ServiceMonitor
serviceMonitor:
  enabled: true
jobs:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: another-node-label-key
            operator: In
            values:
            - another-node-label-value
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: capsule-proxy
  priorityClassName: "system-node-critical"
  nodeSelector:
    node-role.kubernetes.io/master: ""
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
