---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: projectcapsule
spec:
  interval: 30s
  url: https://projectcapsule.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capsule
spec:
  serviceAccountName: kustomize-controller
  interval: 30s
  targetNamespace: capsule-system
  releaseName: "capsule"
  chart:
    spec:
      chart: capsule
      version: "0.7.2"
      sourceRef:
        kind: HelmRepository
        name: projectcapsule
      interval: 24h
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      remediateLastFailure: true
  driftDetection:
    mode: enabled
  values:
    crds:
      install: true
    manager:
      resources: null
      options:
        forceTenantPrefix: false
    options:
      logLevel: 8
