apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.58.0/bundle.yaml
  - cert-manager.flux.yaml
  - capsule.flux.yaml
  - metrics.flux.yaml
