name: Setup caches

description: Setup caches for go modules and build cache.

inputs:
  build-cache-key:
    description: build cache prefix

runs:
  using: composite
  steps:
    - uses: actions/cache@f4b3439a656ba812b8cb417d2d49f9c810103092 # v3.4.0
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('**/go.sum') }}-${{ hashFiles('Makefile') }}
    - uses: actions/cache@f4b3439a656ba812b8cb417d2d49f9c810103092 # v3.4.0
      if: ${{ inputs.build-cache-key }}
      with:
        path: ~/.cache/go-build
        key: ${{ runner.os }}-build-cache-${{ inputs.build-cache-key }}-${{ hashFiles('**/go.sum') }}-${{ hashFiles('Makefile') }}