{{- if and .Values.certManager.generateCertificates .Values.options.enableSSL -}}
  {{- if not .Values.certManager.externalCA.enabled  -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "capsule-proxy.fullname" . }}-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "capsule-proxy.fullname" . }}-selfsigned-ca
spec:
  isCA: true
  commonName: {{ include "capsule-proxy.fullname" . }}-selfsigned-ca
  secretName: {{ include "capsule-proxy.caSecretName" . }}
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ include "capsule-proxy.fullname" . }}-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
  {{- end }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "capsule-proxy.fullname" . }}-ca-issuer
spec:
  ca:
    secretName: {{ include "capsule-proxy.caSecretName" . }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "capsule-proxy.fullname" . }}-serving-cert
spec:
  dnsNames:
  {{- range $hosts := .Values.ingress.hosts }}
  - {{ $hosts.host }}
  {{- end }}
  issuerRef:
    kind: Issuer
    name: {{ include "capsule-proxy.fullname" . }}-ca-issuer
  secretName: {{ include "capsule-proxy.fullname" . }}
  subject:
    organizations:
      - clastix.io
---
{{- end }}