{{- if eq .Values.kind "DaemonSet" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "capsule-proxy.fullname" . }}
  labels:
    {{- include "capsule-proxy.labels" . | nindent 4 }}
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "capsule-proxy.selectorLabels" . | nindent 6 }}
  template:
    {{- include "capsule-proxy.pod" $ | nindent 4 }}
{{- end }}
