apiVersion: v1
kind: Service
metadata:
  name: {{ include "capsule-proxy.fullname"  . }}-metrics-service
  labels:
    {{- include "capsule-proxy.labels"  . | nindent 4 }}
  {{- with .Values.customAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - port: 8080
    name: metrics
    protocol: TCP
    targetPort: 8080
  selector:
    {{- include "capsule-proxy.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
