{{- if and .Values.options.enableSSL .Values.options.generateCertificates -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-certgen"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-certgen"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: "docker.io/jettech/kube-webhook-certgen:v1.3.0"
        args:
            - create
            - --host={{ include "capsule-proxy.fullname" . }}.{{.Release.Namespace}}.svc,{{ include "capsule-proxy.fullname" . }}
            - --namespace=$(NAMESPACE)
            - --secret-name={{ include "capsule-proxy.fullname" . }}
            - --cert-name={{ .Values.options.SSLCertFileName }}
            - --key-name={{ .Values.options.SSLKeyFileName }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      serviceAccountName: {{ include "capsule-proxy.serviceAccountName" . }}
  {{- end }}
